const data = {
    products: [
      // Electronics
      {
        id: 1,
        name: 'Smartphone X',
        slug: 'smartphone-x',
        category: 'Electronics',
        brand: 'TechBrand',
        price: 799,
        rating: 4.5,
        countInStock: 30,
        isFeatured: true,
        newArrival: false,
        image: 'images/eng.jpg',
      },
      {
        id: 2,
        name: 'Wireless Earbuds',
        slug: 'wireless-earbuds',
        category: 'Electronics',
        brand: 'AudioMax',
        price: 149,
        rating: 4.2,
        countInStock: 50,
        isFeatured: false,
        newArrival: true,
        image: 'images/eng2.jpg',
      },
      {
        id: 3,
        name: '4K Ultra TV',
        slug: '4k-ultra-tv',
        category: 'Electronics',
        brand: 'VisionPlus',
        price: 999,
        rating: 4.7,
        countInStock: 20,
        isFeatured: true,
        newArrival: true,
        image: 'images/eng3.jpg',
      },
  
      // Fashion - Men
      {
        id: 4,
        name: 'Leather Jacket',
        slug: 'leather-jacket',
        category: 'Fashion - Men',
        brand: 'UrbanStyle',
        price: 120,
        rating: 4.3,
        countInStock: 15,
        isFeatured: true,
        newArrival: false,
        image: 'images/ind.jpeg',
      },
      {
        id: 5,
        name: 'Running Shoes',
        slug: 'running-shoes',
        category: 'Fashion - Men',
        brand: 'Speedster',
        price: 85,
        rating: 4.1,
        countInStock: 40,
        isFeatured: false,
        newArrival: true,
        image: 'images/ind2.jpeg',
      },
  
      // Fashion - Women
      {
        id: 6,
        name: 'Evening Gown',
        slug: 'evening-gown',
        category: 'Fashion - Women',
        brand: 'EleganceWear',
        price: 250,
        rating: 4.6,
        countInStock: 10,
        isFeatured: true,
        newArrival: false,
        image: 'images/ind3.jpeg',
      },
      {
        id: 7,
        name: 'Designer Handbag',
        slug: 'designer-handbag',
        category: 'Fashion - Women',
        brand: 'ChicBags',
        price: 75,
        rating: 4.4,
        countInStock: 25,
        isFeatured: false,
        newArrival: true,
        image: 'images/nig3.jpg',
      },
  
      // Beauty
      {
        id: 8,
        name: 'Perfume Set',
        slug: 'perfume-set',
        category: 'Beauty',
        brand: 'Scentique',
        price: 60,
        rating: 4.5,
        countInStock: 35,
        isFeatured: true,
        newArrival: true,
        image: 'images/nig4.jpg',
      },
      {
        id: 9,
        name: 'Lipstick Collection',
        slug: 'lipstick-collection',
        category: 'Beauty',
        brand: 'GlamourGloss',
        price: 35,
        rating: 4.3,
        countInStock: 45,
        isFeatured: false,
        newArrival: false,
        image: 'images/nig5.jpg',
      },
  
      // Home Decor
      {
        id: 10,
        name: 'Ceramic Vase',
        slug: 'ceramic-vase',
        category: 'Home Decor',
        brand: 'HomeStyle',
        price: 40,
        rating: 4.2,
        countInStock: 60,
        isFeatured: false,
        newArrival: true,
        image: 'images/nig6.jpg',
      },
      {
        id: 11,
        name: 'Abstract Wall Art',
        slug: 'abstract-wall-art',
        category: 'Home Decor',
        brand: 'ArtisticTouch',
        price: 150,
        rating: 4.8,
        countInStock: 12,
        isFeatured: true,
        newArrival: false,
        image: 'images/wall_art.jpg',
      },
  
      // Sports
      {
        id: 12,
        name: 'Official Football',
        slug: 'official-football',
        category: 'Sports',
        brand: 'SportyPro',
        price: 25,
        rating: 4.4,
        countInStock: 70,
        isFeatured: false,
        newArrival: true,
        image: 'images/football.jpg',
      },
      {
        id: 13,
        name: 'Premium Yoga Mat',
        slug: 'premium-yoga-mat',
        category: 'Sports',
        brand: 'FlexFit',
        price: 30,
        rating: 4.5,
        countInStock: 30,
        isFeatured: true,
        newArrival: false,
        image: 'images/yoga_mat.jpg',
      },
  
      // Kitchen
      {
        id: 14,
        name: 'High-Speed Blender',
        slug: 'high-speed-blender',
        category: 'Kitchen',
        brand: 'KitchenPro',
        price: 55,
        rating: 4.3,
        countInStock: 25,
        isFeatured: false,
        newArrival: true,
        image: 'images/blender.jpg',
      },
      {
        id: 15,
        name: 'Non-stick Cookware Set',
        slug: 'non-stick-cookware-set',
        category: 'Kitchen',
        brand: 'ChefMaster',
        price: 120,
        rating: 4.7,
        countInStock: 18,
        isFeatured: true,
        newArrival: false,
        image: 'images/nig.jpg',
      },
    ],
  };
  export default data;